### ISSUE TITLE
Unable to run ActiveRecord::Base.connection.execute

### ISSUE THREAD

**Issue by marutinandanpandya** [jhollinger/otr-activerecord#12]
Hi, 
using otr-activerecord version 1.2.7, (database.yml is correct and connects to remote RDS) but when I call ActiveRecord::Base execute it tries to connect to localhost
Error Stack
```
[2019-03-18 10:29:06] ERROR PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pg-0.18.4/lib/pg.rb:45:in `initialize'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pg-0.18.4/lib/pg.rb:45:in `new'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pg-0.18.4/lib/pg.rb:45:in `connect'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1010:in `retrieve_connection'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/connection_handling.rb:90:in `connection'
	/usr/local/loc/exporter/app/apis/trips.rb:21:in `block (2 levels) in <class:Trips>'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/grape-1.2.3/lib/grape/endpoint.rb:57:in `call'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/grape-1.2.3/lib/grape/endpoint.rb:57:in `block (2 levels) in generate_api_method'
	/home/deployer/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:170:in `instrument'
....
```

1. Gemfile
```
source 'http://rubygems.org'
gem 'grape', '1.2.3'
gem 'otr-activerecord', '1.2.7'
...
```

2.  config.ru
```
require 'rack'
require 'grape'
require './app/core'

OTR::ActiveRecord.configure_from_file! "config/database.yml"
use OTR::ActiveRecord::ConnectionManagement

run Base
```

3. app/api/trips
```
class Trips < Grape::API
  resource 'trips' do
    desc 'List all trips.'
    get '/' do
      query = "select count(*) from trips group by owner_type;"
      ActiveRecord::Base.connection.execute(query).values
    end

  end
end
```

Does otr-activerecord supports running direct queries, instead of using models?

**Comment by jhollinger** [comment]
Unable to reproduce (at least in recent versions).
