### ISSUE TITLE
Tests fail with activerecord 6.0.x

### ISSUE THREAD

**Issue by dleidert** [jhollinger/otr-activerecord#38]
The Gemfile allows `activerecord` 6.0.x. When executing the tests with this version, the tests fail due to

```
Failures:

  1) OTR::ActiveRecord.configure_from_file! when simple configuration file is given configures active record
     Failure/Error:
       expect(::ActiveRecord::Base.configurations['test']).to eq(
         adapter: 'sqlite3',
         database: 'tmp/simple.sqlite3',
         migrations_paths: ['db/migrate']
       )
     
       expected: {:adapter=>"sqlite3", :database=>"tmp/simple.sqlite3", :migrations_paths=>["db/migrate"]}
            got: {"adapter"=>"sqlite3", "database"=>"tmp/simple.sqlite3", "migrations_paths"=>["db/migrate"]}
     
       (compared using ==)
     
       Diff:
       @@ -1,4 +1,4 @@
       -:adapter => "sqlite3",
       -:database => "tmp/simple.sqlite3",
       -:migrations_paths => ["db/migrate"],
       +"adapter" => "sqlite3",
       +"database" => "tmp/simple.sqlite3",
       +"migrations_paths" => ["db/migrate"],
       
     # ./spec/otr-activerecord/activerecord_spec.rb:9:in `block (4 levels) in <top (required)>'

  2) OTR::ActiveRecord.configure_from_file! when configuration file with multiple roles given configures active record
     Failure/Error:
       expect(::ActiveRecord::Base.configurations['test']).to eq(
         adapter: 'sqlite3',
         database: 'tmp/multi.sqlite3',
         migrations_paths: ['db/migrate']
       )
     
       expected: {:adapter=>"sqlite3", :database=>"tmp/multi.sqlite3", :migrations_paths=>["db/migrate"]}
            got: {"adapter"=>"sqlite3", "database"=>"tmp/multi.sqlite3", "migrations_paths"=>["db/migrate"]}
     
       (compared using ==)
     
       Diff:
       @@ -1,4 +1,4 @@
       -:adapter => "sqlite3",
       -:database => "tmp/multi.sqlite3",
       -:migrations_paths => ["db/migrate"],
       +"adapter" => "sqlite3",
       +"database" => "tmp/multi.sqlite3",
       +"migrations_paths" => ["db/migrate"],
       
     # ./spec/otr-activerecord/activerecord_spec.rb:23:in `block (4 levels) in <top (required)>'

Finished in 0.01645 seconds (files took 0.3151 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/otr-activerecord/activerecord_spec.rb:6 # OTR::ActiveRecord.configure_from_file! when simple configuration file is given configures active record
rspec ./spec/otr-activerecord/activerecord_spec.rb:20 # OTR::ActiveRecord.configure_from_file! when configuration file with multiple roles given configures active record
```

The tests succeed with `activerecord` 6.1.

**Comment by jhollinger** [comment]
Thanks, should be fixed now.
