### ISSUE TITLE
db:seed:dump

### ISSUE THREAD

**Issue by atomless** [jhollinger/otr-activerecord#5]
With the seed_dump gem installed and required into the Rakefile running `rake db:seed:dump` throws this error : 
```BASH
$ rake db:seed:dump --trace
rake aborted!
Don't know how to build task 'db:seed:dump' (see --tasks)
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task_manager.rb:71:in `[]'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:151:in `invoke_task'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/bin/rake:23:in `load'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/bin/rake:23:in `<main>'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

Any ideas on how to get this working? Or know of another way to dump the db contents to seeds.rb ?

**Comment by jhollinger** [comment]
I suspect that gem is using Rails to autoload the tasks, which won't work here. You'll probably have to load the tasks on your own in Rakefile. Maybe `load "tasks/seed_dump.rake"`? Something like that - you might have to poke around a bit in that project to find it.

**Comment by atomless** [comment]
Thanks - will give that a try.

**Comment by atomless** [comment]
ah, then it throws another error:
```
rake aborted!
NameError: uninitialized constant SeedDump::Environment::Rails
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/seed_dump-3.2.4/lib/seed_dump/environment.rb:5:in `dump_using_environment'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/seed_dump-3.2.4/lib/tasks/seed_dump.rake:6:in `block (3 levels) in <top (required)>'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/Users/jamestindall/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/bin/rake:23:in `load'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/bin/rake:23:in `<main>'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/jamestindall/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed:dump
```

**Comment by jhollinger** [comment]
Sounds like that gem is expecting rails to be there. I'm afraid I can't be much detailed help with that. You might want to open an issue in that project and ask if rails can be made optional. Probably isn't that hard to do - might be an easy PR.

**Comment by atomless** [comment]
That's what I thought too - thanks Jordan.
